ALTER PROC CHECK_OUT
@ODA_NO AS TINYINT
AS
DECLARE @MUSTERI_ID AS INT
SET @MUSTERI_ID = (SELECT TOP 1 Musterý_Id FROM Musteri WHERE Oda_No=@ODA_NO)
IF NOT EXISTS( SELECT * FROM ODEMELER WHERE MUSTERI_ID = @MUSTERI_ID)
BEGIN
	DECLARE @TUTAR AS FLOAT
	DECLARE @GIRIS AS DATETIME
	DECLARE @CIKIS AS DATETIME
	DECLARE @EKYATAK AS TINYINT

	SELECT @GIRIS=Giris_Tarihi, @EKYATAK=Ek_Yatak FROM Musteri
	WHERE Musterý_Id = @MUSTERI_ID

	SET @CIKIS = GETDATE()
	SET @TUTAR = (SELECT dbo.UCRET(@ODA_NO, DATEDIFF(DAY,@GIRIS, @CIKIS), @EKYATAK))
	
	INSERT INTO ODEMELER(MUSTERI_ID,TUTAR)
	VALUES (@MUSTERI_ID, @TUTAR)
	PRINT CONCAT_WS(' ', 'ODENECEK TUTAR', @TUTAR, 'TL')
END

DELETE FROM Musteri
WHERE Oda_No = @ODA_NO

UPDATE Odalar
SET Oda_Durumu=1, Kisi_Sayisi = 0
WHERE Oda_No=@ODA_NO

