ALTER FUNCTION BUTONRENK(@ODA_NO TINYINT)
RETURNS CHAR(1)
AS
BEGIN 
	DECLARE @DURUM AS BIT, @KISI AS TINYINT
	SELECT @DURUM=Oda_Durumu, @KISI=Kisi_Sayisi FROM Odalar WHERE Oda_No = @ODA_NO
	
	IF (@DURUM = 1)
	BEGIN
		IF (@KISI > 0)
		BEGIN
			-- ODAYA BEKLENEN VAR SARI BUTON
			RETURN '0'
		END
		-- ODA MÜSAÝT YEÞÝL BUTON
		RETURN '1'
	END
	-- ODA DOLU KIRMIZI BUTON
	RETURN '2'
	
END

SELECT dbo.BUTONRENK(1)

SELECT * FROM Odalar

