ALTER FUNCTION MUSAITODA(
@KISI TINYINT,
@BASLANGIC DATE,
@BITIS DATE,
@EK_YATAK TINYINT = 0)
RETURNS @TBL TABLE (
		ODANO TINYINT
)
AS 
BEGIN
		
		INSERT INTO @TBL(ODANO)
		SELECT O.Oda_No  FROM Odalar O
		-- YETERLÝ SAYIDA EK YATAK OLUP OLMADIÐI
		WHERE (CONVERT(SMALLINT,@KISI) - CONVERT(SMALLINT,Mevcut_Kapasite)) <= CONVERT(SMALLINT, @EK_YATAK) 
		-- HER EK YATAK EKLEMEK 1 KÝSÝ EKLENDÝÐÝ VARSAYIMINA GÖRE ODADAKÝ KÝÞÝ VE EK YATAK SAYISININ ODANIN MAX KAP.'INI GEÇÝP GEÇMEDÝÐÝ
		AND @KISI + @EK_YATAK  <= Max_Kapasite
		AND Oda_Durumu = 1 
		-- AYNI TARÝHLERDE REZ BULUNUP BULUNMAMA
		AND NOT EXISTS (SELECT 1 
						FROM Rezervasyonlar R 
						WHERE R.Oda_No = O.Oda_No
						AND (
						@BASLANGIC BETWEEN R.Rez_baslangic AND R.Rez_bitis
						OR @BITIS BETWEEN R.Rez_baslangic AND R.Rez_bitis
						OR (@BASLANGIC <= R.Rez_baslangic AND @BITIS >= R.Rez_bitis)))			
		RETURN			
END

-- BUNU DATA GRÝDE UYGULAMAYA ÇALIÞCAN
SELECT * FROM Odalar
WHERE Oda_no IN (SELECT ODANO FROM DBO.MUSAITODA(3,GETDATE(),GETDATE(),4))