ALTER PROC REZERVASYON
@TC CHAR(11),
@ISIM VARCHAR(50),
@SOYAD VARCHAR(50),
@MAIL VARCHAR(100),
@DOGUM DATE,
@CINSIYET BIT,
@TELEFON VARCHAR(20),
@BASLANGIC DATE,
@BITIS DATE,
@KISI TINYINT ,
@ODA TINYINT ,
@EK_YATAK TINYINT = 0,
@REZID INT  = 0 OUTPUT -- BU PARAMETREYÝ UYGULAMADA ALIP BÝRDEN ÇOK KÝÞÝNÝN KAYIDI YAPILIYORSA ÝLK IF'IN ELSE BLOÐUNA GÝRMESÝ ÝÇÝN KULLANILACAK
AS
BEGIN
	-- AYNI TARÝHLER ARASINDA AYNI ODAYA BAÞKA REZERVASYON VAR MI
	IF ( NOT EXISTS(SELECT 1 FROM Rezervasyonlar WHERE @BASLANGIC BETWEEN Rez_baslangic AND Rez_bitis AND Oda_No = @ODA) )
	BEGIN
		-- ODA KONTROL
		IF ( EXISTS(SELECT * FROM dbo.MUSAITODA(@KISI,@EK_YATAK)WHERE ODANO = @ODA) )
		BEGIN
				INSERT INTO Musteri(Tc_No, Isim, Soyisim, E_mail, Dogum_Tarihi, Cinsiyet, Telefon, Oda_No)
				VALUES (@TC, @ISIM, @SOYAD, @MAIL, @DOGUM, @CINSIYET, @TELEFON, @ODA)
				-- REZERVASYONLAR TABLOSUNA KAYIT ÝÇÝN ID ALINMASI
				DECLARE @MUSTERID AS INT
				SET @MUSTERID = SCOPE_IDENTITY()
				INSERT INTO Rezervasyonlar( Musterý_Id, Rez_baslangic, Rez_bitis, Oda_No, Kisi_Sayisi, Rez_tarih)
				VALUES (@MUSTERID, @BASLANGIC, @BITIS, @ODA, @KISI, GETDATE())
				SET @REZID = SCOPE_IDENTITY()
				-- KARIÞIKLIK OLMAMASI ÝÇÝN REZERVASYON ANINDAKÝ EK YATAK DA SADECE REZERVASYONU YAPAN KÝÞÝYE EKLENÝYOR
				INSERT INTO MusteriHizmet(Musteri_id, Oda_No, Hizmetid, Adet)
				VALUES(@MUSTERID, @ODA, 1, IIF(@EK_YATAK>0, @EK_YATAK, 0))
				-- ODEME KAYDININ OLUÞTURULMASI
				DECLARE @TUTAR AS FLOAT
				SET @TUTAR = DBO.UCRET(@ODA, DATEDIFF(DAY, @BASLANGIC, @BITIS), @EK_YATAK)
				INSERT INTO ODEMELER(MUSTERI_ID, TUTAR)
				VALUES(@MUSTERID, @TUTAR)
		END
		ELSE
		BEGIN
			RAISERROR('Oda müsait deðil!',16,1)
		END

	END

ELSE
BEGIN
	-- Eðer ayný rezervayona ait bir diðer müþteriyi ekliyorsak sadece müsteri tablosuna eklme yap yeni bir rezervasyon kayýdý yapma
	IF (  @REZID > 0 )
	BEGIN
		INSERT INTO Musteri(Tc_No, Isim, Soyisim, E_mail, Dogum_Tarihi, Cinsiyet, Telefon, Oda_No)
				VALUES (@TC, @ISIM, @SOYAD, @MAIL, @DOGUM, @CINSIYET, @TELEFON, @ODA)
	END
	ELSE
	RAISERROR('Belirtilen tarihte odaya baþka bir rezervasyon bulunuyor',16,1)
END
END


