EXEC REZERVASYON
@ISIM ='MEHMET',
@SOYISIM ='POLAT',
@TCNO ='12345678912',
@DOGUM_TARIH ='20000514',
@CINSIYET=0,
@TELEFON ='05521234567',
@MAIL ='EMÝR@GMAÝL.COM',
@ODA_NO =1,
@BASLANGICTARIHI= '20241020',
@BITISTARIHI = '20241030',
@KISI =2,
@EK_YATAK = 1

-- REZERVASYONLU CHECK IN
EXEC CHECK_IN
@REZ_ID =  3

-- REZERVASYONSUZ CHECK IN
EXEC CHECK_IN
@ISIM = 'MELAHAT',
@SOYISIM  = 'DEMÝR',
@TCNO  = '4879652103',
@DOGUM_TARIH  = '19900821',
@CINSIYET  = 1,
@TELEFON = '05350486955',
@MAIL = 'AYSE@GMAÝL.COM',
@ODA_NO = 1,
@KISI = 1,
@EK_YATAK = 0

-- Check-out deneme
EXEC CHECK_OUT
@ODA_NO = 1


SELECT * FROM Musteri
SELECT * FROM Rezervasyonlar
SELECT * FROM Odalar
SELECT * FROM ODEMELER
SELECT * FROM Musteri_LOG

SELECT * FROM Musteri M 
JOIN Rezervasyonlar R ON M.Musterý_Id=R.Musterý_Id
WHERE R.Musterý_Id=M.Musterý_Id

TRUNCATE TABLE Musteri
TRUNCATE TABLE Rezervasyonlar
TRUNCATE TABLE ODEMELER


UPDATE Odalar
SET Kisi_Sayisi = 0, Oda_Durumu = 1
WHERE Oda_No=1

