-- Konaklama ücretini hesaplamayý saðlayan fonksiyon
ALTER FUNCTION UCRET(@ODA_NO AS TINYINT, @KALINAN_GUN AS INT, @EK_YATAK AS TINYINT)
RETURNS FLOAT
AS
BEGIN
DECLARE @ISLEM BIT 
DECLARE @GECELIK AS FLOAT
DECLARE @RESULT AS FLOAT
SET @GECELIK = (SELECT Gecelik_Ucret FROM Odalar WHERE @ODA_NO = Oda_No)

IF (@ISLEM = 0)
BEGIN
	-- kalýnan gün 0 olursa ücret yanlýþ çýkacaðý için kontrol
	IF @KALINAN_GUN = 0 
		SET @RESULT = @GECELIK + (300 * @EK_YATAK)
	ELSE
		SET @RESULT = (@GECELIK * @KALINAN_GUN) + (300 * @EK_YATAK)

	RETURN @RESULT
	END
END



